### PR TITLE
Esp8266 issues

### PR DESCRIPTION
**Pull request by nailyk-fr**
Add a basic (sorry, too tired to make more for now) `NodeMCU` page to track common issues, as mentioned here https://github.com/nRF24/RF24/issues/244#issuecomment-357211322 and as a solve of https://github.com/nRF24/RF24/issues/449
Two commits as you may want only one of the both.

### CODE REVIEW

**Comment by nailyk-fr** [comment]
Sorry if some typos remains (done in vim :wink: ) . Feels free to ask some changes. 
capture d ecran_2018-12-20_22-31-54
Thanks again for the library !

**Comment by TMRh20** [comment]
Thanks for the additions!

Normally documentation is added by editing the RF24.h file and using markup + HTML syntax to add pages/info. This will ensure that your changes will be saved when the docs are regenerated.

**Comment by nailyk-fr** [comment]
Where are the markup files please ? 

capture d ecran_2018-12-22_13-37-46

**Comment by TMRh20** [comment]
Its all in the main repository (
https://github.com/nRF24/RF24/blob/master/RF24.h )

The markup/html is literally in the main source code. Then I use Doxygen to
generate the files to put on github.io.


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by 2bndy5** [comment]
@nailyk-fr to add a page to the "Related Pages" tab you need to add it to the bottom of the RF24.h file in a separate comment block. Documentation is written in Markdown syntax. Please review doxygen manual (especially the [@page special command](https://www.doxygen.nl/manual/commands.html#cmdpage))

Alternatively, you could add a *nodeMCU.md* file to the root of the RF24 repo and it will automatically get added to the "Related Pages" tab in the docs on next release (please review the [doxygen manual about using separate md files](https://www.doxygen.nl/manual/markdown.html#md_page_header)).

**Pull request closed without merging**
