### PR TITLE
Fixed invalid paths to some RF24 examples

### PR DESCRIPTION
**Pull request by ffoxin**
Some URLs from RF24 documentation returns 404 error.

### CODE REVIEW

**Comment by 2bndy5** [comment]
Not sure this is needed because
1. Links are generated by doxygen
2. These examples are soon to be replaced

**Comment by Avamander** [comment]
Won't hurt though. If things get replaced PRs against docs have to be closed/merged before anyways.

**Comment by 2bndy5** [comment]
>Links are generated by doxygen

I was trying to say that the links *were* not invalid. Merging this just broke the links to [Transfer.cpp](http://tmrh20.github.io/RF24/Transfer_8cpp-example.html) & [GettingStarted.cpp](http://tmrh20.github.io/RF24/GettingStarted_8cpp-example.html)

**Comment by Avamander** [comment]
@2bndy5 ok reverted, so let's just close the PRs and place a redirect (somehow) to the new docs?

**Pull request merged**
