### PR TITLE
add CONTRIBUTING.md & change links to docs

### LINKED ISSUE #8: this repo could use a contributing guidelines file
I think it prudent to have contributing guidelines for this repo because some people may not know about the use of doxygen to document the libraries. I can put together a md file that links to doxygen manual and mentions to look at the libraries' header files.

### PR DESCRIPTION
**Pull request by 2bndy5**
fixes #8

### CODE REVIEW

**Comment by 2bndy5** [comment]
@TMRh20 Do you want me to submit a new doxygen workflow for github actions to the AutoAnalogAudio & TMRpcm repos? It would simplify the guidelines here (not to mention completeness).

**Comment by TMRh20** [comment]
Sure for aaaudio but TMRpcm uses the wiki for documentation.

**Comment by 2bndy5** [comment]
ok I'll do a PR for the AAAudio. I've never tried the wiki option, so I'll have to look into that.

**Comment by 2bndy5** [comment]
I made [another PR to AAAudio](https://github.com/TMRh20/AutoAnalogAudio/pull/16)

I should've realized this before making the commit, but I removed the folders for docs using doxygen (including RF24* & AAAudio) on this branch.

I also adjusted the Contributing guidelines to single-out the TMRpcm lib's docs.

**Comment by 2bndy5** [comment]
Merged all the changes from #9 into this one (for simplicity).

**Pull request merged**
